spring:
  application:
    name: hyperativa
  config:
    import:
      - optional:file:./environments.properties
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    web:
      pageable:
        max-page-size: 2000
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/hyperativa_db?useSSL=false&serverTimezone=UTC
    username: hyperativa
    password: hyperativa
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hyperativa-pool
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 2000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      org.hibernate.envers.audit_strategy: org.hibernate.envers.strategy.DefaultAuditStrategy
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: hyperativa-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: hyperativa-scheduling-
      pool:
        size: 2

server:
  servlet:
    session:
      cookie:
        http-only: true
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 1024
  shutdown:

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

app:
  jwt:
    secret: ""
    expiration: 86400000